### ISSUE TITLE
missing dependensy for git-cola

### ISSUE THREAD

**Issue by peter1000** [NuTyX/extra#7]
I installed git-cola: seems that a few dependencies are missing?

**sip, python-qt4**

```
root [ ~ ]# cards install git-cola
/var/lib/pkg/depotrepo/gui-extra/git-cola/.PKGREPO
/var/lib/pkg/depotrepo/gui-extra/git-cola/git-cola1443040780x86_64.cards.tar.xz
151908 Bytes - 49028 Bytes/Sec - 100% - 0 Sec remain c remain 
Retrieve info about the 278 packages: 100 %
ADD   : git-cola 2.1.1-2, 119 files: 100 %
root [ ~ ]# git-cola
Traceback (most recent call last):
  File "/usr/bin/git-cola", line 55, in <module>
    from cola.app import add_common_arguments
  File "/usr/share/git-cola/lib/cola/app.py", line 20, in <module>
    import sip
ImportError: No module named sip
root [ ~ ]# 
```
```
root [ ~ ]# cards install sip
/var/lib/pkg/depotrepo/cli/sip/.PKGREPO
/var/lib/pkg/depotrepo/cli/sip/sip1442442615x86_64.cards.tar.xz
191404 Bytes - 60380 Bytes/Sec - 100% - 0 Sec remain c remain 
Retrieve info about the 279 packages: 100 %
ADD   : sip 4.16.3-1, 9 files: 100 %
root [ ~ ]# git-cola
Sorry, you do not seem to have PyQt4 installed.
Please install it before using git-cola.
e.g.: sudo apt-get install python-qt4
root [ ~ ]# 
```

```
root [ ~ ]# cards install python-qt4
```

---

After installing: `sip, python-qt4` git-cola opens.

**Comment by tnut** [comment]
commited, Have a look at the Pkgfile, you asks what for is the run variable used for. You should get the answer with this commit (it's specify the non automaticaly found runtime deps)

**Comment by peter1000** [comment]
Thanks
